/**
 * This file is autogenerated, don't edit it!
 *
 * Run `pnpm run x packages/api/tools/generate-ts-types-for-metadata.ts` to update this file.
 */ "use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});


//# sourceMappingURL=metadataFileTypes.js.map